name: mlflow-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.7
  - pip
  - pip:
      - mlflow==2.15.1
      - cloudpickle==3.1.2
      - numpy==2.2.3
      - pandas==2.2.3
      - psutil==6.1.1
      - pyarrow==22.0.0
      - scikit-learn==1.5.2
      - scipy==1.15.2
